### ISSUE TITLE
When I use http proxy to get https url, The operation was canceled.

### ISSUE THREAD

**Issue by forconz** [matteocontrini/PlainHttp#1]
HTTPS proxies are not supported on .NET?

I try connected to HTTPS endpoint via HTTP proxy:
```
            IHttpRequest request = new HttpRequest("https://www.google.com/")
            {
                Timeout = TimeSpan.FromSeconds(2),
                Proxy = new Uri("http://xxxuser:xxxxffff@315.118.118.186:3008")
            };

```

PlainHttp.HttpRequestTimeoutException: Failed request: [GET https://www.google.com/] [The operation was canceled.]
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
   at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at PlainHttp.HttpRequest.SendAsync(CancellationToken cancellationToken) in .\PlainHttp\HttpRequest.cs:line 141
   --- End of inner exception stack trace ---
   at PlainHttp.HttpRequest.SendAsync(CancellationToken cancellationToken) in .\PlainHttp\HttpRequest.cs:line 158
   at .ShoppingService.Execute(Account account, Shopping shopping, CancellationToken cancellationToken) in .\ShoppingService.cs:line 173
   at .ShoppingService.<>c__DisplayClass5_0.<<Shopping>b__0>d.MoveNext() in .\ShoppingService.cs:line 110
PlainHttp.HttpRequestTimeoutException: Failed request: [GET https://www.google.com/] [The operation was canceled.]
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
   at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at PlainHttp.HttpRequest.SendAsync(CancellationToken cancellationToken) in .\PlainHttp\HttpRequest.cs:line 141
   --- End of inner exception stack trace ---
   at PlainHttp.HttpRequest.SendAsync(CancellationToken cancellationToken) in .\PlainHttp\HttpRequest.cs:line 158
   at .ShoppingService.Execute(Account account, Shopping shopping, CancellationToken cancellationToken) in .\ShoppingService.cs:line 173
   at .ShoppingService.<>c__DisplayClass5_0.<<Shopping>b__0>d.MoveNext() in .\ShoppingService.cs:line 110

**Comment by matteocontrini** [comment]
What you're trying to do is indeed supported, I personally do that extensively in a project.

The exception you're reporting is a bit cryptic but it could point to a problem with the proxy. Did you perhaps try to run the request with another external tool, like Postman or curl, to assess whether it's something related to .NET?

**Comment by forconz** [comment]
I run SwitchyOmega which is a extension of chrome, I config the proxy, chrome work well via proxy.

```
            IHttpRequest request = new HttpRequest("https://www.google.com/")
            {
                Timeout = TimeSpan.FromSeconds(2)
            };
            IHttpResponse response = await request.SendAsync();
```
I removed the proxy, and the request work well. response.Succeeded is true.

**Comment by forconz** [comment]
"http://xxxuser:xxxxffff@315.118.118.186:3008" is a wrong proxy, the right proxy had been modified before I post this issue.

Only the 'http' scheme is allowed for the proxy, but I connected to "https://www.google.com/" via the HTTP proxy, the exception  occurred.

**Comment by forconz** [comment]
TaskCanceledException is probably correct. Something caused the HttpClient to cancel the request, most likely due to the HttpClient.Timeout occurring. 

```
            IHttpRequest request = new HttpRequest("https://www.google.com/")
            {
                // Timeout = TimeSpan.FromSeconds(2),
                Proxy = new Uri("http://xxxuser:xxxxffff@315.118.118.186:3008")
            };
```

The commented code let proxy work well.

```
            Stopwatch stopWatch = new Stopwatch();
            stopWatch.Start();
            IHttpResponse response = await request.SendAsync();
            stopWatch.Stop();
            _logger.LogInformation($"#{Thread.CurrentThread.ManagedThreadId} HttpRequest with proxy({account.ProxyUri}), Elapsed {stopWatch.Elapsed.TotalMilliseconds} milliseconds.");

```

Elapsed 3.4s...

So, The operation was canceled, because the request is timeout!
